language: python

branches:
  only:
    - master

python:
  - '3.6'

cache: pip

install:
  - pip install -r requirements.txt
  - pip install flake8 mypy

script:
  - flake8 github_unfollower.py
  - mypy github_unfollower.py || true
