language: python

branches:
  only:
    - master

python:
  - '3.6'

cache: pip

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run black --check github_unfollower.py
  - pipenv run mypy github_unfollower.py || true
  - pipenv run pylint github_unfollower.py || true
